# fly.toml app configuration file generated for anonde-platform on 2026-05-13T20:43:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anonde-platform"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.anonde"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 25

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/healthz"
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  cpu_kind = 'shared'
  cpus = 4
  memory = '2gb'
  memory_mb = 2048
  processes = ['app']
  size = 'shared-cpu-4x'
