# fly.toml app configuration file generated for anonde-platform on 2026-05-12T21:39:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'anonde-platform'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile.platform'

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  checks = [{ grace_period = '5s', interval = '10s', method = 'GET', path = '/healthz', protocol = 'http', timeout = '2s', tls_skip_verify = false }]
  concurrency = { hard_limit = 100, soft_limit = 25, type = 'requests' }
  force_https = true
  internal_port = 8080
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '2gb'
  memory_mb = 2048
  processes = ['app']
  size = 'shared-cpu-1x'
