package api

import (
	"context"
	"errors"
	"strings"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	anondev1 "github.com/anonde-io/anonde/gen/anonde/v1"
	"github.com/anonde-io/anonde/internal/core"
)

// GRPCServer satisfies the generated ServiceServer interface so
// the same Service can be exposed over (a) native gRPC and (b) the REST
// gateway generated by protoc-gen-grpc-gateway. Both transports share
// the proto_logic.go conversions; this file is just the gRPC method
// signatures plus gRPC-status error mapping.
//
// Error mapping vs ConnectServer: gRPC uses codes from
// google.golang.org/grpc/codes and the gateway translates them to HTTP
// statuses (InvalidArgument → 400, PermissionDenied → 403, NotFound →
// 404, ResourceExhausted → 429, Internal → 500). The fallback is
// InvalidArgument for validation-shaped errors and NotFound for
// "not found" wording that Service.Reveal / Detokenize emit when the
// anonymization is missing.
type GRPCServer struct {
	anondev1.UnimplementedServiceServer
	svc *core.Service
}

func NewGRPCServer(svc *core.Service) *GRPCServer {
	return &GRPCServer{svc: svc}
}

func (s *GRPCServer) CreateAnonymization(ctx context.Context, req *anondev1.CreateAnonymizationRequest) (*anondev1.CreateAnonymizationResponse, error) {
	resp, err := executeCreate(ctx, s.svc, req)
	if err != nil {
		return nil, grpcErrFor(err)
	}
	return resp, nil
}

func (s *GRPCServer) DetokenizeTokens(ctx context.Context, req *anondev1.DetokenizeTokensRequest) (*anondev1.DetokenizeTokensResponse, error) {
	resp, err := executeDetokenize(ctx, s.svc, req)
	if err != nil {
		return nil, grpcErrFor(err)
	}
	return resp, nil
}

func (s *GRPCServer) RevealContent(ctx context.Context, req *anondev1.RevealContentRequest) (*anondev1.RevealContentResponse, error) {
	resp, err := executeReveal(ctx, s.svc, req)
	if err != nil {
		return nil, grpcErrFor(err)
	}
	return resp, nil
}

func (s *GRPCServer) SynthesizeContent(ctx context.Context, req *anondev1.SynthesizeContentRequest) (*anondev1.SynthesizeContentResponse, error) {
	resp, err := executeSynthesize(ctx, s.svc, req)
	if err != nil {
		return nil, grpcErrFor(err)
	}
	return resp, nil
}

func (s *GRPCServer) DeleteAnonymization(ctx context.Context, req *anondev1.DeleteAnonymizationRequest) (*anondev1.DeleteAnonymizationResponse, error) {
	resp, err := executeDelete(ctx, s.svc, req)
	if err != nil {
		return nil, grpcErrFor(err)
	}
	return resp, nil
}

func (s *GRPCServer) GetVersion(ctx context.Context, _ *anondev1.GetVersionRequest) (*anondev1.GetVersionResponse, error) {
	resp, err := executeGetVersion(ctx, s.svc)
	if err != nil {
		return nil, status.Error(codes.Internal, err.Error())
	}
	return resp, nil
}

func (s *GRPCServer) HealthCheck(_ context.Context, _ *anondev1.HealthCheckRequest) (*anondev1.HealthCheckResponse, error) {
	return executeHealthCheck(), nil
}

// grpcErrFor maps a Service error to a gRPC status error.
//
// Detection rule mirrors connectErrFor + adds "not found" → NotFound so
// REST clients see HTTP 404 for missing-anonymization errors instead of
// HTTP 400. Service does not yet have a typed ErrNotFound; using a
// substring match keeps the change local. Promote to a typed sentinel
// once we have a durable store and care about precise error semantics.
func grpcErrFor(err error) error {
	if err == nil {
		return nil
	}
	if errors.Is(err, core.ErrPolicyDenied) {
		return status.Error(codes.PermissionDenied, err.Error())
	}
	if strings.Contains(err.Error(), "not found") {
		return status.Error(codes.NotFound, err.Error())
	}
	return status.Error(codes.InvalidArgument, err.Error())
}
