#!/usr/bin/env python3
"""loader — fetch WNUT-17 emerging-entities NER (test split), sample N
sentences, emit anonde corpus.jsonl with gold PERSON / LOCATION /
ORGANIZATION spans.

WNUT-17 (Derczynski et al., 2017) is the standard English NER benchmark
for *noisy* user-generated text: tweets, Reddit comments, YouTube
descriptions. Compared to CoNLL-2003 (clean newswire), it tests
robustness to:
  - Informal capitalisation ("apple watch", not "Apple Watch")
  - Code-switched fragments
  - Emerging entities not in pretraining vocab
  - Typos, slang, brand stylisations

WNUT-17 entity types: person, location, group, corporation, product,
creative-work. We map:
  person      -> PERSON
  location    -> LOCATION
  corporation -> ORGANIZATION
  group       -> ORGANIZATION
  product, creative-work -> drop (no anonde canonical mapping)

Output schema matches the rest of bench/corpora/* — one JSON per line:

    {"id": "wnut-17-NNNN", "text": "...", "entities": [
      {"start": int, "end": int, "type": "PERSON" | "LOCATION" | "ORGANIZATION"}
    ]}
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

# WNUT-17 raw tag -> anonde canonical. Pre-mapped to base tag (BIO
# prefix stripped) for the lookup.
RAW2TYPE = {
    "person": "PERSON",
    "location": "LOCATION",
    "corporation": "ORGANIZATION",
    "group": "ORGANIZATION",
    # creative-work, product → intentionally dropped.
}

# Authoritative id-to-tag list, from leondz/wnut_17 features.ner_tags
# ClassLabel (also same in tner/wnut2017's features when accessible).
# 0 = O; B-/I- pairs in this exact order:
ID2TAG = [
    "O",
    "B-corporation", "I-corporation",
    "B-creative-work", "I-creative-work",
    "B-group", "I-group",
    "B-location", "I-location",
    "B-person", "I-person",
    "B-product", "I-product",
]

# Cap streaming work — WNUT-17 test split is ~1287 sentences; 3000 is a
# safe upper bound.
MAX_STREAM = 3000

# Preferred dataset id + revision pairs. The original `wnut_17` builder
# is script-based and refused by `datasets >= 4`. The `refs/convert/
# parquet` ref on the same repo (and its mirrors) is auto-generated by
# HF and works without a script. We try the canonical leondz mirror
# first since its ClassLabel matches ID2TAG above.
CANDIDATES: list[tuple[str, str | None, str, str | None]] = [
    ("leondz/wnut_17", None, "test", "refs/convert/parquet"),
    ("wnut_17", None, "test", "refs/convert/parquet"),
    ("tner/wnut2017", None, "test", "refs/convert/parquet"),
]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--n", type=int, default=300,
                    help="number of sentences to sample")
    ap.add_argument("--seed", type=int, default=20260515)
    args = ap.parse_args()

    try:
        from datasets import load_dataset
    except ImportError:
        print("missing dep: pip install datasets", file=sys.stderr)
        return 2

    rng = random.Random(args.seed)

    ds = None
    chosen: tuple[str, str | None, str, str | None] | None = None
    errors: list[str] = []
    for repo, cfg, split, rev in CANDIDATES:
        try:
            kwargs: dict = dict(split=split, streaming=True)
            if rev is not None:
                kwargs["revision"] = rev
            if cfg is not None:
                ds = load_dataset(repo, cfg, **kwargs)
            else:
                ds = load_dataset(repo, **kwargs)
            chosen = (repo, cfg, split, rev)
            break
        except Exception as e:  # noqa: BLE001
            errors.append(f"{repo}({cfg}/{split}/@{rev}): {str(e)[:160]}")
            continue
    if ds is None:
        print("wnut_17: no mirror resolved.", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        return 2

    reservoir: list = []
    n_seen = 0
    try:
        for i, ex in enumerate(ds):
            n_seen = i + 1
            if i < args.n:
                reservoir.append(ex)
            else:
                j = rng.randrange(0, i + 1)
                if j < args.n:
                    reservoir[j] = ex
            if i >= MAX_STREAM:
                break
    except Exception as e:  # noqa: BLE001
        print(f"stream from {chosen!r} failed after {n_seen} examples: {e}",
              file=sys.stderr)
        return 2

    if not reservoir:
        print(f"no examples streamed from {chosen!r}", file=sys.stderr)
        return 2

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    n_emitted = 0
    n_spans = 0
    with out_path.open("w", encoding="utf-8") as fh:
        for idx, ex in enumerate(reservoir):
            tokens = ex.get("tokens") or ex.get("words") or []
            tag_ids = ex.get("ner_tags") or ex.get("tags") or []
            if not tokens or len(tokens) != len(tag_ids):
                continue

            # Build text + char-offset map (codepoint indices).
            text_parts: list[str] = []
            tok_starts: list[int] = []
            cursor = 0
            for ti, tok in enumerate(tokens):
                if ti > 0:
                    text_parts.append(" ")
                    cursor += 1
                tok_starts.append(cursor)
                text_parts.append(tok)
                cursor += len(tok)
            text = "".join(text_parts)
            tok_ends = [s + len(tokens[i]) for i, s in enumerate(tok_starts)]

            # Walk BIO tags into spans. A span starts at B-X and runs
            # over contiguous I-X tags of the same base type.
            entities = []
            i = 0
            while i < len(tag_ids):
                tid = tag_ids[i]
                tag = ID2TAG[tid] if 0 <= tid < len(ID2TAG) else "O"
                if tag == "O" or "-" not in tag:
                    i += 1
                    continue
                _, kind = tag.split("-", 1)
                start_tok = i
                j = i + 1
                while j < len(tag_ids):
                    ntid = tag_ids[j]
                    nxt = ID2TAG[ntid] if 0 <= ntid < len(ID2TAG) else "O"
                    if nxt == f"I-{kind}":
                        j += 1
                        continue
                    break
                entity_type = RAW2TYPE.get(kind)
                if entity_type:
                    entities.append({
                        "start": tok_starts[start_tok],
                        "end": tok_ends[j - 1],
                        "type": entity_type,
                    })
                    n_spans += 1
                i = j

            fh.write(json.dumps({
                "id": f"wnut-17-{idx:04d}",
                "text": text,
                "entities": entities,
            }, ensure_ascii=False) + "\n")
            n_emitted += 1

    print(f"wrote {out_path}: {n_emitted} docs, {n_spans} gold spans "
          f"(avg {n_spans/max(n_emitted,1):.1f} spans/doc) "
          f"[mirror: {chosen[0]}/{chosen[1]}/{chosen[2]}@{chosen[3] or 'main'}]",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
